apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin
  name: admin
spec:
  type: NodePort
  ports:
    - name: "admin-service"
      port: 3001
      targetPort: 3001
      nodePort: 30002
  selector:
    app: admin
