apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  type: NodePort
  ports:
    - name: "backend-service"
      port: 5000
      targetPort: 5000
      nodePort: 30001
  selector:
    app: backend