apiVersion: v1
kind: Service
metadata: 
  labels:
    app: frontend
  name: frontend
spec:
  type: NodePort
  ports:
    - name: "frontend-service"
      port: 3000
      targetPort: 3000
      nodePort: 30000
  selector:
    app: frontend
